// Gerado a partir dos metadados do Wikimedia Commons. Não edite à mão sem conferir a licença.
export type PhotoInfo = {
  src: string;
  width: number;
  height: number;
  credit: { author: string; license: string; licenseUrl: string; source: string };
};

export const photos = {
  "dest-buenos-aires": { src: "/images/fotos/dest-buenos-aires.jpg", width: 1440, height: 1800, credit: { author: "ProtoplasmaKid", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:Vista_a%C3%A9rea_de_Plaza_de_Mayo_02.jpg" } },
  "dest-cancun": { src: "/images/fotos/dest-cancun.jpg", width: 1351, height: 1689, credit: { author: "Autor não informado", license: "CC0", licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en", source: "https://commons.wikimedia.org/wiki/File:Canc%C3%BAn,_Q.R.,_MX.jpg" } },
  "dest-gramado": { src: "/images/fotos/dest-gramado.jpg", width: 1600, height: 2000, credit: { author: "AUGUSTO JANISKI JUNIOR", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:GRAMADO_-_RIO_GRANDE_DO_SUL_-_BRASIL_BY_AUGUSTO_JANISCKI_JUNIOR_(14281915950).jpg" } },
  "dest-lisboa": { src: "/images/fotos/dest-lisboa.jpg", width: 1440, height: 1800, credit: { author: "Dale Cruse - 10M views from San Francisco, CA, USA", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0", source: "https://commons.wikimedia.org/wiki/File:Alfama_Rooftops_and_Tagus_River_View,_Lisbon_(54733698959).jpg" } },
  "dest-maceio": { src: "/images/fotos/dest-maceio.jpg", width: 1600, height: 2000, credit: { author: "Marinelson Almeida - Traveling through Brazil from Niteroi, Brasil", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Praia_de_Paju%C3%A7ara_-_Macei%C3%B3_-_Alagoas_(13125463894).jpg" } },
  "dest-paris": { src: "/images/fotos/dest-paris.jpg", width: 1600, height: 2000, credit: { author: "Yann Caradec from Paris, France", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0", source: "https://commons.wikimedia.org/wiki/File:La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques,_Paris_ao%C3%BBt_2014_(2).jpg" } },
  "gal-dubai": { src: "/images/fotos/gal-dubai.jpg", width: 3200, height: 2133, credit: { author: "Norlando Pobre", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Dubai_Marina_Skyline.jpg" } },
  "gal-gramado": { src: "/images/fotos/gal-gramado.jpg", width: 3200, height: 2133, credit: { author: "Yeuxpapilon", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:Lago_Negro_Gramado.jpg" } },
  "gal-lisboa": { src: "/images/fotos/gal-lisboa.jpg", width: 3200, height: 2137, credit: { author: "Jakub Hałun", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0", source: "https://commons.wikimedia.org/wiki/File:Est%C3%A1tua_de_D._Jos%C3%A9_na_Pra%C3%A7a_do_Com%C3%A9rcio,_Lisbon,_Portugal,_20250604_1826_9450.jpg" } },
  "gal-maceio": { src: "/images/fotos/gal-maceio.jpg", width: 3200, height: 2133, credit: { author: "Marinelson Almeida - Traveling through Brazil from Niteroi, Brasil", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Ponta_Verde_-_Macei%C3%B3_-_Alagoas_(16363389968).jpg" } },
  "gal-maldivas": { src: "/images/fotos/gal-maldivas.jpg", width: 3200, height: 1802, credit: { author: "Martin Falbisoner", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:Diamonds_Thudufushi_Beach_and_Water_Villas,_May_2017_-09.jpg" } },
  "gal-paris": { src: "/images/fotos/gal-paris.jpg", width: 3200, height: 1797, credit: { author: "Benh LIEU SONG", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:Paris_Night_(banner_esvoy).jpg" } },
  "gal-rio": { src: "/images/fotos/gal-rio.jpg", width: 3200, height: 2133, credit: { author: "Wilfredor", license: "CC0", licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en", source: "https://commons.wikimedia.org/wiki/File:Copacabana,_Rio_de_Janeiro,_Brazil.jpg" } },
  "gal-santorini": { src: "/images/fotos/gal-santorini.jpg", width: 3200, height: 1800, credit: { author: "Radek Kucharski from Warsaw, Poland", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:White_houses_of_Oia_on_Santorini_(52181448879).jpg" } },
  "hero-noronha": { src: "/images/fotos/hero-noronha.jpg", width: 3200, height: 2000, credit: { author: "Danilo de Castro", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0", source: "https://commons.wikimedia.org/wiki/File:Praia_do_Le%C3%A3o.jpg" } },
  "inspira-iguacu": { src: "/images/fotos/inspira-iguacu.jpg", width: 1600, height: 2000, credit: { author: "Marinelson Almeida - Traveling through Brazil from Niteroi, Brasil", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:275_waterfalls_of_all_shapes_and_sizes_in_a_single_place._That%27s_Foz_de_Igua%C3%A7u_in_Brazil._(18722604451).jpg" } },
  "inspira-lencois": { src: "/images/fotos/inspira-lencois.jpg", width: 1600, height: 2000, credit: { author: "Paulo Cattelan", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:Parque_Nacional_dos_Len%C3%A7%C3%B3is_Maranhenses_Paulo_Cattelan_(03).jpg" } },
  "inspira-machu-picchu": { src: "/images/fotos/inspira-machu-picchu.jpg", width: 1600, height: 2000, credit: { author: "Diego Delso", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:Machu_Picchu,_Per%C3%BA,_2015-07-30,_DD_40.JPG" } },
  "inspira-maldivas": { src: "/images/fotos/inspira-maldivas.jpg", width: 1460, height: 1825, credit: { author: "Matheenfaiz", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:Anantara_Kihavah_-_Aerial_Hero_Shot_2024.jpg" } },
  "inspira-nova-york": { src: "/images/fotos/inspira-nova-york.jpg", width: 1490, height: 1862, credit: { author: "Jakub Hałun", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0", source: "https://commons.wikimedia.org/wiki/File:Brooklyn_Bridge_and_Manhattan,_New_York_City,_20231005_1101_2190.jpg" } },
  "inspira-porto-de-galinhas": { src: "/images/fotos/inspira-porto-de-galinhas.jpg", width: 1600, height: 2000, credit: { author: "Marinelson Almeida - Traveling through Brazil from Niteroi, Brasil", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Jangadas_em_Porto_de_Galinhas_-_Pe_-_Brasil._(7489892142).jpg" } },
  "inspira-roma": { src: "/images/fotos/inspira-roma.jpg", width: 1600, height: 2000, credit: { author: "Livioandronico2013", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:Colosseum_and_Arch_of_Constantine_seen_from_Palatine.jpg" } },
  "inspira-salvador": { src: "/images/fotos/inspira-salvador.jpg", width: 1600, height: 2000, credit: { author: "MTur Destinos", license: "Public domain", licenseUrl: "https://commons.wikimedia.org/wiki/Commons:Licensing", source: "https://commons.wikimedia.org/wiki/File:MARCIO_FILHO_PELOURINHO_SALVADOR_BAHIA_(40369900734).jpg" } },
} as const satisfies Record<string, PhotoInfo>;

export type PhotoKey = keyof typeof photos;
